version: "3.3"
services:
  zuulserver:
    image: 192.168.0.158:5000/xiaoji-zuulserver
    hostname: zuulserver
    configs:
      - source: zuul_config
        target: /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/application.properties

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-aac:
    image: 192.168.0.158:5000/xiaoji-sa-aac
    hostname: sa-aac
    configs:
      - source: aac_config
        target: /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/application.properties

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-aba:
    image: 192.168.0.158:5000/xiaoji-sa-aba
    hostname: sa-aba
    configs:
      - source: aba_config
        target: /usr/local/tomcat/webapps/aba/WEB-INF/classes/application.properties

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-abc:
    image: 192.168.0.158:5000/xiaoji-sa-abc
    hostname: sa-abc
    configs:
      - source: abc_config
        target: /usr/local/tomcat/webapps/abc/WEB-INF/classes/application.properties

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-abd:
    image: 192.168.0.158:5000/xiaoji-sa-abd
    hostname: sa-abd
    configs:
      - source: abd_config
        target: /usr/local/tomcat/webapps/abd/WEB-INF/classes/application.properties

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-aad:
    image: 192.168.0.158:5000/xiaoji-sa-aad
    hostname: sa-aad
    configs:
      - source: aad_config
        target: /usr/verticles/aad.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

configs:
  zuul_config:
    file: ./zuulserver/application.properties
  aac_config:
    file: ./aac/application.properties
  aba_config:
    file: ./aba/application.properties
  abc_config:
    file: ./abc/application.properties
  abd_config:
    file: ./abd/application.properties
  aad_config:
    file: ./aad/aad.json

networks:
  mwxing-network-overlay:
    external: true
