include:
  - source: xunfei/aiui
    generators:
      - name: 意图事件发生器
        identify: events_generator_with_intent
        flow: flow_events_generator_with_intent
      - name: 技能事件发生器
        identify: events_generator_with_service
        flow:
          <<: *flow_events_generator_with_service
  - source: github
  - source: mwxing
deploy:
  force: false
flows:
  - flow_events_genfor_github_push:
      name: Github代码库变动处理流
      trigger: flow_events_genfor_github_push
      hostname: flow_gitpush
      parameters:
        - github_app
        - event
      follows:
        - name: 代码库变动事件数据转换
          trigger: translate_gitpush_to_service_events
          parameters:
            - datasource;$.parent.parameters
          outputs:
            - cleaned
          next:
            - name: 发送变动事件数据
              trigger: exc
              parameters:
                - method;post
                - urlabs;http://sa-aag:8080/aag/webhooks/event.internal/v1/#{observer}
                - params;$.root.parameters.event.output
                - data;$.parent.outputs.cleaned
                - merge_payload;$.root.parameters
              outputs:
                - executed
  - flow_events_generator_with_intent: &flow_events_generator_with_intent
      name: 意图事件发生器处理流
      trigger: flow_events_generator_with_intent
      hostname: flow_1
      parameters:
        - github_app
        - clientip
        - event
      follows:
        - name: 意图事件数据转换
          trigger: translate_aiui_to_intent_events
          parameters:
            - datasource;$.parent.parameters
          outputs:
            - cleaned
          next:
            - name: 发送意图事件数据
              trigger: exc
              parameters:
                - method;post
                - urlabs;http://sa-aag:8080/aag/webhooks/event.internal/v1/#{observer}
                - params;$.root.parameters.event.output
                - data;$.parent.outputs.cleaned
                - merge_payload;$.root.parameters
              outputs:
                - executed
executors:
  - translate_aiui_to_intent_events:
      name: 讯飞AIUI数据转换意图事件数据
      hostname: nashorn_1
      container: acj
      scriptengine: Nashorn
      clean: |
        function clean(datasource) {
          var result = {};

          print('Start Nashorn Javascript processing...');
          print(datasource);

          // filter source code here start
          var eventsource = JSON.parse(datasource);
          var input = eventsource.event.output.payload.xunfeiyun;
          var data = input.data[0];

          var event = {
            category: 'xunfei/aiui',
            type: 'intent'
          };

          for (var di in input.data) {
            var dt = input.data[di];
            if (dt['sub'] === 'nlp' && dt['intent']['service'] && dt['intent']['intentType'] === 'custom' && dt['intent']['semantic']) {
              event['service'] = dt['intent']['service'];

              var semantics = dt['intent']['semantic'];

              for (var sei in semantics) {
                var semantic = semantics[sei];

                event['intent'] = semantic['intent'];
              }
            }
          }

          var outputs = {
            event: event,
            xunfeiyun: input
          };

          print(JSON.stringify(outputs));

          // filter source code here end
          return JSON.stringify(outputs);
        }
  - translate_gitpush_to_service_events:
      name: Github变动数据转换变动事件数据
      hostname: nashorn_gitpush
      container: acj
      scriptengine: Nashorn
      clean: |
        function clean(datasource) {
          var result = {};

          print('Start Nashorn Javascript processing...');
          print(datasource);

          // filter source code here start
          var eventsource = JSON.parse(datasource);
          var eventload = eventsource.event.output;

          var event = {
            category: eventload.webhook,
            observer: eventload.observer,
            type: eventload.event,
            repository: eventload.payload.repository.full_name,
            modified: eventload.payload.repository.head_commit.modified
          };

          var outputs = {
            event: event,
            github: eventload.payload
          };

          print(JSON.stringify(outputs));

          // filter source code here end
          return JSON.stringify(outputs);
        }
dispatch:
  events:
    - name: 触发意图事件转换
      type: WEBHOOK
      id: nautilus_xj-gtd/gtd2_follow_webhook_xunfei.aiui_notification
      event: WEBHOOK_XUNFEI.AIUI
      filters:
        - name: webhook
          value: xunfei.aiui
        - name: observer
          value: 43193b8cbd26b614fbc4b4885a9a512740a2df35
      flow: flow_events_generator_with_intent
    - name: 触发Github代码库变动事件转换
      type: GITHUB_APP
      id: nautilus_xj-gtd/gtd2_follow_github_app_notification
      event: GITHUB_APP
      filters:
        - name: webhook
          value: github_app
        - name: event
          value: push
        - name: observer
          value: 43193b8cbd26b614fbc4b4885a9a512740a2df35
      flow: flow_events_genfor_github_push
