version: "3.3"
services:
  sa-aup:
    image: 192.168.0.158:5000/xiaoji-sa-aup
    hostname: sa-aup
    configs:
      - source: aup_config
        target: /usr/verticles/aup.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-agd:
    image: 192.168.0.158:5000/xiaoji-sa-agd
    hostname: sa-agd
    configs:
      - source: agd_config
        target: /usr/local/tomcat/webapps/agd/WEB-INF/classes/application.properties

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-sms:
    image: 192.168.0.158:5000/xiaoji-sa-sms
    hostname: sa-sms
    configs:
      - source: sms_config
        target: /usr/local/tomcat/webapps/sms/WEB-INF/classes/application.properties

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-mif:
    image: 192.168.0.158:5000/xiaoji-sa-mif
    hostname: sa-mif

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-bla:
    image: 192.168.0.158:5000/xiaoji-sa-bla
    hostname: sa-bla
    configs:
      - source: bla_config
        target: /usr/local/tomcat/webapps/bla/WEB-INF/classes/application.properties

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-bac:
    image: 192.168.0.158:5000/xiaoji-sa-bac
    hostname: sa-bac

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-bal:
    image: 192.168.0.158:5000/xiaoji-sa-bal
    hostname: sa-bal
    configs:
      - source: bal_config
        target: /usr/verticles/bal.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-sha:
    image: 192.168.0.158:5000/xiaoji-sa-sha
    hostname: sa-sha
    configs:
      - source: sha_config
        target: /usr/verticles/sha.json
      - source: sha_chinese_holiday_2019_config
        target: /opt/duan/sha/plan/chinese_holiday_2019.json
      - source: sha_chinese_holiday_2019_agendas_config
        target: /opt/duan/sha/plan-agendas/chinese_holiday_2019.json
      - source: sha_chinese_famous_2019_config
        target: /opt/duan/sha/plan/chinese_famous_2019.json
      - source: sha_chinese_famous_2019_agendas_config
        target: /opt/duan/sha/plan-agendas/chinese_famous_2019.json
      - source: sha_chinese_follow_2019_config
        target: /opt/duan/sha/plan/chinese_follow_2019.json
      - source: sha_chinese_follow_2019_agendas_config
        target: /opt/duan/sha/plan-agendas/chinese_follow_2019.json
      - source: sha_shanghai_animation_exhibition_2019_config
        target: /opt/duan/sha/plan/shanghai_animation_exhibition_2019.json
      - source: sha_shanghai_animation_exhibition_2019_agendas_config
        target: /opt/duan/sha/plan-agendas/shanghai_animation_exhibition_2019.json
      - source: sha_west_holiday_2019_config
        target: /opt/duan/sha/plan/west_holiday_2019.json
      - source: sha_west_holiday_2019_agendas_config
        target: /opt/duan/sha/plan-agendas/west_holiday_2019.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

configs:
  aup_config:
    file: ./aup/aup.json
  agd_config:
    file: ./agd/application.properties
  sms_config:
    file: ./sms/application.properties
  bla_config:
    file: ./bla/application.properties
  bal_config:
    file: ./bal/bal.json
  sha_config:
    file: ./sha/sha.json
  sha_chinese_holiday_2019_config:
    file: ./sha/sha/plan/chinese_holiday_2019.json
  sha_chinese_famous_2019_config:
    file: ./sha/sha/plan/chinese_famous_2019.json
  sha_chinese_follow_2019_config:
    file: ./sha/sha/plan/chinese_follow_2019.json
  sha_shanghai_animation_exhibition_2019_config:
    file: ./sha/sha/plan/shanghai_animation_exhibition_2019.json
  sha_west_holiday_2019_config:
    file: ./sha/sha/plan/west_holiday_2019.json
  sha_chinese_holiday_2019_agendas_config:
    file: ./sha/sha/plan-agendas/chinese_holiday_2019.json
  sha_chinese_famous_2019_agendas_config:
    file: ./sha/sha/plan-agendas/chinese_famous_2019.json
  sha_chinese_follow_2019_agendas_config:
    file: ./sha/sha/plan-agendas/chinese_follow_2019.json
  sha_shanghai_animation_exhibition_2019_agendas_config:
    file: ./sha/sha/plan-agendas/shanghai_animation_exhibition_2019.json
  sha_west_holiday_2019_agendas_config:
    file: ./sha/sha/plan-agendas/west_holiday_2019.json

networks:
  mwxing-network-overlay:
    external: true
