version: "3.3"
services:
  sa-cdc:
    image: 192.168.0.158:5000/xiaoji-sa-cdc
    hostname: sa-cdc
    configs:
      - source: cdc_config
        target: /usr/verticles/cdc.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-sho:
    image: 192.168.0.158:5000/xiaoji-sa-sho
    hostname: sa-sho

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-aah:
    image: 192.168.0.158:5000/xiaoji-sa-aah
    hostname: sa-aah

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-aag:
    image: 192.168.0.158:5000/xiaoji-sa-aag
    hostname: sa-aag
    configs:
      - source: aag_config
        target: /usr/verticles/aag.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-sas:
    image: 192.168.0.158:5000/xiaoji-sa-sas
    hostname: sa-sas
    configs:
      - source: sas_config
        target: /usr/verticles/sas.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-exc:
    image: 192.168.0.158:5000/xiaoji-sa-exc
    hostname: sa-exc
    configs:
      - source: exc_config
        target: /usr/verticles/exc.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-acj:
    image: 192.168.0.158:5000/xiaoji-sa-acj
    hostname: sa-acj
    configs:
      - source: acj_config
        target: /usr/verticles/acj.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-wti:
    image: 192.168.0.158:5000/xiaoji-sa-wti
    hostname: sa-wti
    configs:
      - source: wti_config
        target: /usr/verticles/wti.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-ips:
    image: 192.168.0.158:5000/xiaoji-sa-ips
    hostname: sa-ips
    configs:
      - source: ips_config
        target: /usr/verticles/ips.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-nlp:
    image: 192.168.0.158:5000/xiaoji-sa-nlp
    hostname: sa-nlp
    configs:
      - source: nlp_config
        target: /usr/verticles/nlp.json
      - source: nlp_markup
        target: /usr/verticles/userdefined.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-pin:
    image: 192.168.0.158:5000/xiaoji-sa-pin
    hostname: sa-pin
    configs:
      - source: pin_config
        target: /usr/verticles/pin.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  sa-ann:
    image: 192.168.0.158:5000/xiaoji-sa-ann
    hostname: sa-ann
    configs:
      - source: ann_config
        target: /usr/verticles/ann.json

    networks:
      - mwxing-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

configs:
  cdc_config:
    file: ./cdc/cdc.json
  nlp_config:
    file: ./nlp/nlp.json
  nlp_markup:
    file: ./nlp/userdefined.json
  sas_config:
    file: ./sas/sas.json
  exc_config:
    file: ./exc/exc.json
  acj_config:
    file: ./acj/acj.json
  wti_config:
    file: ./wti/wti.json
  ips_config:
    file: ./ips/ips.json
  ann_config:
    file: ./ann/ann.json
  pin_config:
    file: ./pin/pin.json
  aag_config:
    file: ./aag/aag.json

networks:
  mwxing-network-overlay:
    external: true
